---
- name: "Ensure authentication method"
  hashivault_auth_method:
    method_type: userpass

- name: "Ensure userpass for user viewer"
  hashivault_userpass:
    name: "{{ item.name }}"
    pass: "{{ item.pass }}"
    policies: "{{ item.policies }}"
  no_log: True
  loop: "{{ vault_service_accounts }}"
  loop_control:
    label: "{{ item.name }}"
  when: vault_service_accounts is defined

- name: "Ensure identity for users"
  hashivault_identity_entity:
    name: "{{ item.name }}"
    policies: default
  loop: "{{ vault_service_accounts }}"
  loop_control:
    label: "{{ item.name }}"
  when: vault_service_accounts is defined

- name: "Read identity for user viewer"
  hashivault_read:
    secret: /identity/entity/name/viewer
  register: hv_identity_viewer

- name: "Read authentication backends"
  hashivault_auth_list:
  register: hv_auth_list

- name: "Ensure alias for user viewer"
  hashivault_identity_entity_alias:
    name: viewer
    canonical_id: "{{ hv_identity_viewer['value']['id'] }}"
    mount_accessor: "{{ hv_auth_list['backends']['userpass/']['accessor'] }}"

- name: "Ensure identity groups"
  hashivault_identity_group:
    name: "{{ item.name }}"
    policies: "{{ item.policies }}"
    member_entity_ids: "{{ item.member_entity_ids | default(omit) }}"
  loop:
  - name: full_admins
    policies: ["full_admin"]
  - name: readonly_admins
    policies: ["readonly_admin"]
    member_entity_ids: "{{ hv_identity_viewer['value']['id'] }}"
  loop_control:
    label: "{{ item.name }}"
