---
- environment:
    VAULT_TOKEN: "{{ vault_root_token }}"
  block:
  - name: "Ensure secret engine"
    hashivault_secret_engine:
      name: transit

  - include_tasks:
      file: auto_unseal.yml
    vars:
      autounseal_name: "{{ item }}"
    loop: "{{ vault_autounseal_endpoints }}"

  - name: "Create long-lived unseal token"
    hashivault_token_create:
      display_name: "auto_unseal_{{ item }}"
      policies: ["{{ item }}"]
      renewable: True
      ttl: 8640h
    tags:
    # this task always changes, which is expected behaviour because it should always create a new token
    - molecule-idempotence-notest
    loop: "{{ vault_autounseal_endpoints }}"
    register: cps2_unseal_tokens

  - include_tasks:
      file: token_exporter/{{ vault_autounseal_token_exporter | default('debuglog') }}.yml
    tags:
    # the goal is to create an always-changed-side-effect.. Skip idempotency test
    - molecule-idempotence-notest
