---
- name: "Ensure local policy files"
  copy:
    src: "{{ item }}.hcl"
    dest: "/tmp/{{ item }}.hcl"
  loop:
  - "full_admin"
  - "readonly_admin"
  - "token_create"

- name: "Ensure hashivault policy's"
  hashivault_policy:
    name: "{{ item }}"
    rules_file: "/tmp/{{ item }}.hcl"
  loop:
  - "full_admin"
  - "readonly_admin"
  - "token_create"

- name: "Ensure admin token"
  hashivault_token_create:
    display_name: admin
    policies: ["full_admin"]
    renewable: True
    period: 120m
  register: hashivault_admin_token
  changed_when: False

- name: "Ensure admin token fact"
  set_fact:
    vault_admin_token: "{{ hashivault_admin_token.token.auth.client_token }}"

- name: "Ensure secret engine"
  hashivault_secret_engine:
    name: transit

- name: "Ensure autounseal configuration"
  include_tasks:
    file: autounseal.yml
  vars:
    autounseal_name: "{{ item }}"
  loop:
  - cps2npo
  - cps2prd
  - aixinfra
