---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint: |
    yamllint . --config-file molecule/yaml-lint.yml
platforms:
- name: vault_infra
  hostname: vault_infra
  image: ${VAULT_IMAGE}
  command: server
  exposed_ports:
  - "8200"
  published_ports:
  - "0.0.0.0:8200:8200"
  env:
    VAULT_LOCAL_CONFIG: |-
      {
        "backend": {
          "file": {
            "path": "/vault/file"
          }
        },
        "default_lease_ttl": "1h",
        "max_lease_ttl": "8640h",
        "listener": {
          "tcp": {
            "address": "0.0.0.0:8200",
            "tls_disable": 1
          }
        },
        "ui": false
      }
  privileged: True
  pre_build_image: True
- name: vault_k8s
  hostname: vault_k8s
  exposed_ports:
  - "8200"
  published_ports:
  - "0.0.0.0:8201:8200"
  image: ${VAULT_IMAGE}
  # using a sleep until the config file appears (see side_effect.yml)
  # because we will only know the auto-unseal config after the role was run on vault_infra
  command: |
    sh -c 'while sleep 1; do \
      [ -f /config.hcl ] && /usr/local/bin/docker-entrypoint.sh server -config=/config.hcl; \
      printf "%s Waiting for config.hcl\n" date; \
    done'
  privileged: True
  pre_build_image: True
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
    prepare: prepare.yml
  inventory:
    host_vars:
      vault_infra:
        molecule_test: True
        vault_infra_addr: ${VAULT_ADDR}
        # what exporter should be used (where to store generated tokens)
        # "hostfact" (see /tasks/token_exporter/hostfact.yml) is required for the pytests and side_effect.yml to work
        vault_autounseal_token_exporter: hostfact
        vault_autounseal_endpoints:
        - k8s
        - k8s_two
      vault_k8s:
        molecule_test: True
        vault_infra_addr: ${VAULT_ADDR}
scenario:
  name: default
  create_sequence:
  - create
  - prepare
  converge_sequence:
  - create
  - prepare
  - converge
  - side_effect
  test_sequence:
  - lint
  - destroy
  - syntax
  - create
  - prepare
  - converge
  - idempotence
  - side_effect
  - verify
  - cleanup
  - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
