---
- name: Gather vault_infra facts
  hosts: vault_infra

# This side-effect sets the secondary vault to auto-unseal
- name: Unseal vault_k8s
  hosts: vault_k8s
  become: True
  tasks:
  - name: "autounseal(vault_k8s): Ensure config"
    vars:
      autounseal_token: "{{ hostvars['vault_infra']['ansible_local']['infra_connection']['k8s_unseal_token'] }}"
      autounseal_name: "k8s"
      autounseal_address: "http://{{ vault_infra_addr }}:8200"
      # autounseal_address: "http://{{ hostvars['vault_infra']['ansible_local']['infra_connection']['ip_address'] }}:8200"
    template:
      dest: /config.hcl
      src: config.hcl.j2

  - environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    block:
    - name: "autounseal(vault_k8s): Read ansible status"
      hashivault_status:
      register: hashivault_status
      until: hashivault_status.status.initialized is defined

    - name: "autounseal(vault_k8s): Ensure vault is initialized"
      hashivault_init:
        recovery_shares: "1"
        recovery_threshold: "1"
      register: hashivault_init
      when: not hashivault_status.status.initialized

    - name: Create facts.d
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: "autounseal(vault_k8s): Ensure vault secrets fact"
      template:
        src: secrets.fact.j2
        dest: /etc/ansible/facts.d/secrets.fact
      vars:
        vault_init_keys: "{{ hashivault_init.recovery_keys_base64 }}"
      when: hashivault_init.changed
